const guests = [
  'PR Indonesia',
  'Edison Panjaitan & Keluarga (Kantor Advokat Panjaitan & Rekan)',
  'Weshley Hutagalung, S.Sos (Pengamat Olahraga & Konsultan Media)',
  'Sigit Nugroho, M.I.Kom. (ICON PR Indonesia)',
  'Dr. Ina Heliani, MH. (Ka. Prodi Ilmu Hukum)',
  'Nita Putri',
  'Dhea Zauta',    
  'Dosen Fakultas Ilmu Komunikasi Universitas Mpu Tantular',
  'Horas Hutauruk (Ka. Biro Administrasi Akademik)',
  'Siti Silaen & Tim PMB Universitas Mpu Tantular',
  'David M Sihombing (Ka. Biro Administrasi Umum)',
  'Abraham & Keluarga',
  'Ratna Aldo (Sari Ayu Martha Tilaar)',
  'Edison H Manurung & Rekan',
  'Rico Hutabarat',
  'Achmad Nurul Syahrahman (Sahabat Karang Taruna Jak-Bar)',
  'Titiek Surya Ningsih, M.Si.',
  'Nova Sari Permata, SE., M.AK',
  'Eka & Keluarga (Bank Rakyat Indonesia)',
  'Allen Nainggolan (Perwakilan Hermione & Kolagen)',
  'Toni Limbong & Keluarga (Pemred Jayapos.co)',
  'Jonro Munthe & Keluarga (Pemred Majalah Narwastu)',
  'Wilson Lalengke & Keluarga (Pemred Media PPWI)',
  'Lusiana & Keluarga',
  'Hertiana & Keluarga',
  'Shinta & Keluarga (Alumni Fikom UMT)',
  'Drs. Tri Adi Sarwoko, M.I.Kom (Ka. Prodi Ilmu Komunikasi)',
  'Witardi Gondowarsito, ST., M.Kom (Ka. Prodi Teknik Informatika)',
  'Bantu Hotsan Simanulang, ST., MT. (Ka. Prodi Teknik Mesin)',
  'Pahala Sinambela, ST., MT. (Ka. Prodi Teknik Elektro)',
  'Franka Hendra Sukma, ST., MT., IPM. (Ka. Prodi Teknik Industri)',
  'Mandiri Jaya Sukses',
  'Diky Soemarno',
  'Mukhlis',
  'Arie Putri',
  'Dolfi Donnofan',
  'Pengajian Ummahat',
  'Hadinoor Gorbachev',
  'Lukman Hakim',
  'Novia Iklima',
  'Ria Maryana',
  'Su Cen',
  'Winda Ayu',
  'Promotor PT Midea Planet Indonesia',
  'dr. Zinita Mutalib',
  'dr. Devi Wallad',
  'Rosa - LSM Srikandi Sejati',
  'Willy Wisnuadhi',
  'Erwin Rosmali',
  'Fitri Astuti',
  'Soni',
  'Agus W.',
  'PT. Soa Cipta Jaya',
  'Fikri',
  'Fauzi',
  'H. Abdul',
  'Ahmad',
  'Khafidoh',
  'Muaekob',
  'Raditya Yuka',
  'Ritme Cipta Karya',
  'Isabel',
  'Ica Ramawisari, ST., MT.',
  'Reva',
  'Ardi',
  'Michael Sitanggang',
  'Ali Munandar',
  'Anna Sofiana',
  'Sanny Kurniawan',
  'Aulia Rahmawati',
  'Didi Kuswanto',
  'Manoban',
  'Umi Engkom',
  'Dewi',
  'Endang Supriatna',
  'Muthia Kirana',
  'Risandi Susanto',
  'Merli Sidik',
  'M. Rivaldi',
  'Amalia Qibthiya',
  'Iptu Nosim Santoso',
  'David Haras',
  'ALL Spareparts Bekasi',
  'Hrs Part Online Shop',
  'Amelia Putri',
  'Aulia Collection',
  'Sariah Nurdeli Widjaja',
  'Team Juara Fibernet',
  'Es Teh Solo Omah Joglo',
  'Sutinah',
  'Dwi Eka',
  'Annisa Pramudya',
  'H. Ghofar',
  'CV. Adi Karya Tehnik',
  'Team Futsal Avogadro',
  'Mohamad Ridwan'
];

export const convertToSlug = (text) => {
  return text
    .toLowerCase()
    .replace(/[.,\s]+/g, '-') // Menghapus koma, titik, dan mengganti spasi dengan strip
    .replace(/-+/g, '-') // Menghilangkan strip berlebih
    .replace(/[^\w\s-&,]/g, '') // Memperbolehkan koma, strip, dan karakter & dalam URL
    .replace(/-$/, ''); // Menghapus strip dari akhir teks jika ada
      // .replace(/[^a-z0-9-,]/g, '') // Memperbolehkan koma dan strip dalam URL
};

export default guests;
